---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash

      cf push "${CF_APP}" -i 1 -d mybluemix.net -n ${CF_APP} --no-start

      name=`cf services | grep Auto-Scaling | awk '{print $1}'`
      if [ -z "$name" ]
      then
        echo "No name found"
        cf create-service Auto-Scaling free BlueMessenger-autoscaling
        cf bind-service "${CF_APP}" BlueMessenger-autoscaling
      else
        echo "$name is the Auto-Scaling name"
        cf bind-service "${CF_APP}" $name
      fi

      name=`cf services | grep MonitoringAndAnalytics | awk '{print $1}'`
      if [ -z "$name" ]
      then
        echo "No name found"
        cf create-service MonitoringAndAnalytics Free BlueMessenger-monitoringandanalytics
        cf bind-service "${CF_APP}" BlueMessenger-monitoringandanalytics
      else
        echo "$name is the MonitoringAndAnalytics name"
        cf bind-service "${CF_APP}" $name
      fi

      cf create-service cloudantNoSQLDB Shared BlueMessenger-cloudant
      cf bind-service "${CF_APP}" BlueMessenger-cloudant

      cf start "${CF_APP}"
